spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    topicToRead: order-topic
    topicToWrite: order-status-service
    kafkaMessageGroupId: "kafka-message-group-id"
server:
      port: 8081